# ======================================================== #
# jumpsuits
- type: loadoutGroup
  id: FloofSecurityJumpsuits
  abstract: true
  loadouts:
  - UniformJumpsuitSecSummer

# ======================================================== #
# HOS additions
- type: loadoutGroup
  id: FloofHosGloves
  abstract: true
  loadouts:
  - HandsHeadSecurityWarmers
  - ClothingHandsSecurityWarmers

- type: loadoutGroup
  id: FloofUndergarmentTopHOS
  parent: FloofUndergarmentTopPassenger
  loadouts: [] # Nuthing here yet

- type: loadoutGroup
  id: FloofUndergarmentBottomHOS
  parent: FloofUndergarmentBottomPassenger
  loadouts:
  - UniformHeadSecurityThong
  - UniformSecurityThong

- type: loadoutGroup
  id: FloofSocksHOS
  parent: FloofSocksPassenger
  loadouts:
  - UnderSocksHeadSecurity
  - ClothingUnderSocksSecurity

#hos pdas
- type: loadoutGroup
  id: FloofHoSPDAs
  name: loadout-group-hos-pdas
  loadouts:
  - HoSPDA
  - ChiefOfSecurityPDA
  - SecurityDirectorPDA
  - SheriffPDA
  - ClothingNeckCollarEmotionalSupportHOS # emotional support


# ======================================================== #
# security officer additions
- type: loadoutGroup
  id: FloofSecurityOfficerJumpsuit
  abstract: true
  loadouts:
  - UniformSecCatsuit

- type: loadoutGroup
  id: FloofSecurityOfficerGloves
  abstract: true
  loadouts:
  - ClothingHandsSecurityWarmers

- type: loadoutGroup
  id: FloofUndergarmentTopSecurityOfficer
  parent: FloofUndergarmentTopPassenger
  loadouts: [] # Nuthing here yet

- type: loadoutGroup
  id: FloofUndergarmentBottomSecurityOfficer
  parent: FloofUndergarmentBottomPassenger
  loadouts:
  - UniformSecurityThong

- type: loadoutGroup
  id: FloofSocksSecurityOfficer
  parent: FloofSocksPassenger
  loadouts:
  - ClothingUnderSocksSecurity

# ======================================================== #
# detective additions
- type: loadoutGroup
  id: FloofDetectiveJumpsuit
  abstract: true
  loadouts: []

- type: loadoutGroup
  id: FloofDetectiveOuterClothing
  abstract: true
  loadouts:
  - OuterCoatDetective

- type: loadoutGroup
  id: FloofDetectiveGloves
  name: loadout-group-security-detective-gloves
  parent: [SecurityGloves]
  loadouts:
  - HandsGlovesForensic
  - ClothingHandsDetectiveWarmers

- type: loadoutGroup
  id: FloofDetectiveShoes
  name: loadout-group-security-detective-shoes
  parent: [SecurityShoes]
  loadouts: []

- type: loadoutGroup
  id: FloofUndergarmentTopDetective
  parent: FloofUndergarmentTopPassenger
  loadouts: [] # Nuthing here yet

- type: loadoutGroup
  id: FloofUndergarmentBottomDetective
  parent: FloofUndergarmentBottomPassenger
  loadouts:
  - UniformDetectiveThong

- type: loadoutGroup
  id: FloofSocksDetective
  parent: FloofSocksPassenger
  loadouts:
  - ClothingUnderSocksDetective

# ======================================================== #
# corpsman additions
- type: loadoutGroup
  id: FloofCorpsmanJumpsuit
  abstract: true
  loadouts: []

- type: loadoutGroup
  id: FloofCorpsmanGloves
  name: loadout-group-security-corpsman-gloves
  parent: [MedicalGloves]
  loadouts:
  - ClothingHandsCorpsmanWarmers

- type: loadoutGroup
  id: FloofCorpsmanShoes
  name: loadout-group-security-corpsman-shoes
  parent: [SecurityShoes]
  loadouts:
  - ClothingShoesColorBlack

- type: loadoutGroup
  id: FloofUndergarmentTopCorpsman
  parent: FloofUndergarmentTopPassenger
  loadouts: [] # Nuthing here yet

- type: loadoutGroup
  id: FloofUndergarmentBottomCorpsman
  parent: FloofUndergarmentBottomPassenger
  loadouts:
  - UniformCorpsmanThong

- type: loadoutGroup
  id: FloofSocksCorpsman
  parent: FloofSocksPassenger
  loadouts:
  - ClothingUnderSocksCorpsman

# ======================================================== #
# Security Technician additions
- type: loadoutGroup
  id: FloofSecurityTechnicianBelts
  name: loadout-group-security-technician-belts
  minLimit: 1
  maxLimit: 1
  loadouts:
  - ClothingBeltCombatUtilityFilled
  - ClothingBeltCombatUtilityAdvanced


# ======================================================== #
# emotional support
- type: loadoutGroup
  id: FloofSecurityCadetPdas
  name: loadout-group-security-cadet-pdas
  minLimit: 1
  maxLimit: 1
  loadouts:
  - SecurityCadetPDA
  - ClothingNeckCollarEmotionalSupportSecCadet

- type: loadoutGroup
  id: FloofSecurityOfficerPdas
  abstract: true
  loadouts:
  - ClothingNeckCollarEmotionalSupportSecOfficer

- type: loadoutGroup
  id: FloofSecurityTechnicianPdas
  name: loadout-group-security-sechtech-pdas
  minLimit: 1
  maxLimit: 1
  loadouts:
  - SecurityTechnicianPDA
  - SecuritySapperPDA
  - ClothingNeckCollarEmotionalSupportSecTech

- type: loadoutGroup
  id: FloofSecurityDetectivePdas
  name: loadout-group-security-detective-pdas
  minLimit: 1
  maxLimit: 1
  loadouts:
  - DetectivePDA
  - ClothingNeckCollarEmotionalSupportDetective

- type: loadoutGroup
  id: FloofSecurityCorpsmanPdas
  name: loadout-group-security-corpsman-pdas
  minLimit: 1
  maxLimit: 1
  loadouts:
  - BrigmedicPDA
  - ClothingNeckCollarEmotionalSupportCorpsman

- type: loadoutGroup
  id: FloofSecurityPrisonguardPdas
  name: loadout-group-security-prisonguard-pdas
  minLimit: 1
  maxLimit: 1
  loadouts:
  - PrisonGuardPDA
  - ClothingNeckCollarEmotionalSupportPrisonGuard

- type: loadoutGroup
  id: FloofSecuritySeniorOfficerPdas
  name: loadout-group-security-seniorofficer-pdas
  minLimit: 1
  maxLimit: 1
  loadouts:
  - SeniorOfficerPDA
  - ClothingNeckCollarEmotionalSupportSeniorOfficer

- type: loadoutGroup
  id: FloofSecurityWardenPdas
  name: loadout-group-security-warden-pdas
  minLimit: 1
  maxLimit: 1
  loadouts:
  - WardenPDA
  - ClothingNeckCollarEmotionalSupportWarden
