- type: gameMapPool
  id: DefaultMapPool
  maps:
  # Euphoria/Panta-Rhei/Floofstaion. We maintain our own map pool.
  # Upstream maps changed to fit our fork with no active maintainer (Dunrab supports them)
  - Arena
  - Edge
  - Pebble
  - TheHive
  - Lighthouse
  # Maintainer: Dunrab
  - Hammurabi # - Delta v says they will be updating this map so we will either have to take out or let it run as is
  - Submarine # Preserved from old Delta-V where it was removed
  - Core # Port from Wizden
  - Meta # Port from Wizden
  - Kettle # Port from Wizden
  - Fland # Port from Wizden
  - Train # Port from Wizden
  - Getaway # Dunrab's own map
  # Maintainer: WhiteLightningTwister
  - Glacier
  - Shoukou # uncertain about this one
  # Unknown/no maintainer, these maps are different from delta-v ones (?)
  - Rad
  - Amber
  - Saltern
  - Tortuga
  - Mesa
  - Asterisk
